import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton_SC, Anton  } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  variable: "--font-anton",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} h-full antialiased text-[calc(100vw / 1440)]`}
    >
      <body className="min-h-full flex flex-col text-[16rem]">
          {/* <main className="bg-gray-900"> */}
          {children}
          {/* </main> */}
        </body>
    </html>
  );
}
